name: arrr
description: Basic Flutter Template built GetX as a state management solution in mind..


version: 1.0.0+1


environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.2

  # GetX
  get: ^4.6.1

  # TODO: Change package name and remove this package 
  change_app_package_name: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  